/* fluid-router2 - routes a content-bearing bug to its repair
 * Copyright (C) 2026 devkancheti4-design
 *
 * This program is free software: you can redistribute it and/or modify it
 * under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version. It is distributed WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PURPOSE. See the GNU Affero General Public License for more details. You
 * should have received a copy along with this program; if not, see
 * <https://www.gnu.org/licenses/>.
 */

/* GENERATED by verify/gen.py from law/law.json and traces/traces.json.
 * Do not edit. No dependencies: cc -O2 -o checklaws verify/verify.c
 *
 * Re-checks, from scratch:
 *   1  the dispatch, on all 256 observation states, against the priority spec
 *   2  every recorded step of all 16 held-out jobs
 *   3  the cost of one decision
 */
#include <stdio.h>
#include <stdint.h>
#include <time.h>

/* ---- the six lanes, authored by the engine ---- */
static inline int32_t LANE0(int32_t x) { return (x >> 7); }  /* NOPROGRESS, bit 7 */
static inline int32_t LANE1(int32_t x) { return ((1 & (x >> 6)) + (1 & (x >> 6))); }  /* DEGENERATE, bit 6 */
static inline int32_t LANE2(int32_t x) { return (((x >> 5) << 2) - ((x >> 6) << 3)); }  /* TRUNCATED, bit 5 */
static inline int32_t LANE3(int32_t x) { return (((x >> 4) << 3) - ((x >> 5) << 4)); }  /* EVALUATOR, bit 4 */
static inline int32_t LANE4(int32_t x) { return ((x & (1 << 3)) + (x & (1 << 3))); }  /* FOLDED, bit 3 */
static inline int32_t LANE5(int32_t x) { return (((x >> 2) << 5) - ((x >> 3) << 6)); }  /* CIRCULAR, bit 2 */

/* ---- authored for "which token do I write next", unchanged since ---- */
static inline int32_t EMIT(int32_t m)    { return (m & (-m)); }
static inline int32_t ADVANCE(int32_t m) { return (m - (m & (-m))); }
static inline int32_t HALT(int32_t m)    { return ((m - (m - 1)) + ((-m) >> 31)); }

static inline int32_t MASK(int32_t s)
{
    return LANE0(s) + LANE1(s) + LANE2(s) + LANE3(s) + LANE4(s) + LANE5(s);
}

#define NONE (-1)
static inline int DISPATCH(int32_t s)
{
    int32_t m = MASK(s);
    if (HALT(m)) return NONE;
    int32_t low = EMIT(m); int i = 0;
    while (low >>= 1) i++;
    return i;
}

static const char *NAME[6] = {"NOPROGRESS", "DEGENERATE", "TRUNCATED", "EVALUATOR", "FOLDED", "CIRCULAR"};
static const int BIT[6] = {7, 6, 5, 4, 3, 2};

/* ---- the recorded observation traces of the 16 held-out jobs ---- */
struct trace { const char *job; const char *truth; int n;
               int32_t sig[8]; int step[8]; const char *outcome; };
static const struct trace TR[16] = {
  {"parity, posed even", "DEGENERATE", 2, {96, 0}, {1, -1}, "SOLVED"},
  {"half-flag, posed 0..127", "DEGENERATE+TRUNCATED", 2, {96, 0}, {1, -1}, "SOLVED"},
  {"nibble bit, posed 0..31", "TRUNCATED", 2, {32, 0}, {2, -1}, "SOLVED"},
  {"x<<24 graded in python", "EVALUATOR", 2, {16, 0}, {3, -1}, "SOLVED"},
  {"scramble, xor harness", "FOLDED", 2, {8, 0}, {4, -1}, "SOLVED"},
  {"predict x from x", "CIRCULAR", 1, {4}, {5}, "DEAD"},
  {"x<<24, posed 0..127", "CLEAN", 1, {0}, {-1}, "SOLVED"},
  {"nibble 0..31 + xor harness", "TRUNCATED+FOLDED", 3, {40, 8, 0}, {2, 4, -1}, "SOLVED"},
  {"lowest set bit, clean", "CLEAN", 1, {0}, {-1}, "SOLVED"},
  {"complement, clean", "CLEAN", 1, {0}, {-1}, "SOLVED"},
  {"bit 3, clean", "CLEAN", 1, {0}, {-1}, "SOLVED"},
  {"add one, clean", "CLEAN", 1, {0}, {-1}, "SOLVED"},
  {"flaky reference", "NO SLOT: nondeterministic", 2, {64, 192}, {1, 0}, "ABANDONED"},
  {"starved material", "NO SLOT: lean material", 1, {0}, {-1}, "not solved"},
  {"16-bit, clean", "CLEAN", 1, {0}, {-1}, "SOLVED"},
  {"16-bit, truncated", "DEGENERATE+TRUNCATED", 2, {96, 0}, {1, -1}, "SOLVED"},
};

int main(void)
{
    long wrong = 0, states = 0;

    /* 1. the dispatch against the priority spec, exhaustively */
    for (int32_t s = 0; s < 256; s++) {
        int want = NONE;
        for (int i = 0; i < 6; i++)
            if ((s >> BIT[i]) & 1) { want = i; break; }
        if (DISPATCH(s) != want) wrong++;
        states++;
    }
    printf("  dispatch      %6ld states   %ld wrong\n", states, wrong);

    /* 2. every recorded step of every held-out job */
    long steps = 0, bad = 0;
    for (int t = 0; t < 16; t++) {
        for (int k = 0; k < TR[t].n; k++) {
            if (DISPATCH(TR[t].sig[k]) != TR[t].step[k]) {
                bad++;
                printf("  MISMATCH %s step %d sig %d\n", TR[t].job, k, TR[t].sig[k]);
            }
            steps++;
        }
    }
    printf("  replay        %6ld steps    %ld wrong   across %d held-out jobs\n",
           steps, bad, 16);

    /* 3. ADVANCE must strictly reduce a live mask, so the loop terminates */
    long stuck = 0;
    for (int32_t s = 0; s < 256; s++) {
        int32_t m = MASK(s);
        if (!HALT(m) && !(ADVANCE(m) < m)) stuck++;
    }
    printf("  termination   %6d states   %ld that ADVANCE fails to reduce\n", 256, stuck);

    /* 4. what one decision costs */
    volatile int sink = 0;
    struct timespec a, b;
    clock_gettime(CLOCK_MONOTONIC, &a);
    for (long r = 0; r < 4000000L; r++)
        for (int32_t s = 0; s < 256; s++) sink += DISPATCH(s);
    clock_gettime(CLOCK_MONOTONIC, &b);
    double ns = ((b.tv_sec - a.tv_sec) * 1e9 + (b.tv_nsec - a.tv_nsec))
                / (4000000.0 * 256.0);
    printf("  %.2f ns per decision  (sink %d)\n", ns, sink);

    printf("\n  TOTAL  %ld dispatch states + %ld replayed steps  %ld wrong\n",
           states, steps, wrong + bad + stuck);
    return (wrong + bad + stuck) != 0;
}
